instabot.py
change like_in_day to like_per_day for consistency
=> Update instabot.py - comment/instructsions consistency

README.md, example.py, instabot.py
Spelling errors, bug fixes and unfollow timer
=> Spelling errors, bug fixes and unfollow timer

unfollowpub.py
based on userinfo.py 
allows you to unsubscribe from unwanted subscriptions
=> unfollow feature

unfollowpub.py
рассмотрел способы нахождения разности в списках при более чем 10000 записей в них
этот вариант во много раз быстрее предыдущего
=> more faster lists subtraction

README.md
Im tested the bot in new enviroment.
=> Updated the tested enviroment.

instabot.py, userinfo.py
Delete some problems like multiple comments on same media, comment our own media, follow our own profile and like our own media.
=> Fix comment, follow and like

instabot.py
Proxy support, format of the proxy:
Proxy without authentication: proxy:port
Proxy with authentication: user:pass@proxy:port
=> Proxy support

src/instabot.py
str was falling over, change to unicode has fixed it on my end. Is there a test suite for this?
=> fixed unicode error on media like

README.md
Add links to places where we can discuss issues without having to create new issues on this repo.
Closes #232
=> Add Community links to readme

src/instabot.py
reverted changes from the running hours
=> reverted last changes

example.py, src/instabot.py
There are some accounts I want to follow and the bot shouldn't unfollow them even if all other conditions for a unfollow apply.
I added an username-based whitelist to make this possible, before unfollowing the bot checks against this list and chooses another random account to unfollow if the username is on the whitelist.
The example.py file has been updated to reflect these changes.
=> Added Unfollow Whitelist

src/instabot.py
Instagram changed some things, the updated instabot.py file makes the unfollow function work again.
=> fix the unfollow bug in instabot.py

src/feed_scanner.py, src/recent_feed.py, src/unfollow_protocol.py
They appear to have changed this again, this function should probably be made 'smarter' at some point and hunt for username/id patterns in the results
I've tested my changes against mode 1, probably not as thoroughly as I'd like to, but it's getting late.
I will at some point run through the entire project and have a major tidy up when I have a chance.
=> Media node JSON correction

src/instabot.py
Fixed Unfollow Log String for the new_auto_mod
=> Fixed Unfollow Log String

.gitignore, example.py, src/feed_scanner.py, src/follow_protocol.py, src/instabot.py, src/likers_graber_protocol.py, src/likers_protocol.py, src/new_auto_mod_like2.py, src/new_auto_mod_likeall.py, src/new_auto_mod_unfollow2.py, src/new_unfollow.py, src/post_page.py, src/recent_feed.py, src/unfollow_protocol.py, src/unfollowpub.py, src/user_feed.py, src/user_feed_protocol.py, src/user_info.py, src/userinfo.py, src/username_checker.py
This is my initial cleanup before making any major changes.
There's a lot more to do in terms of being PEP8 compliant:
- Module and function docstrings
- Line length constraints
- Legal variable and constant naming
- Consistent usage of conditional strings (is, and) vs (==, =, !=) etc.
- Less reuse of code
- Better modular design
- Unit testing
=> Intitial PEP8 cleanup and miscellaneous fixes

src/instabot.py
remove duplicated comment in generate_comment() function
=> remove duplicated comment

src/instabot.py, src/post_page.py, src/recent_feed.py, src/user_feed.py, src/user_info.py
There is no need to load whole page when only json part is needed
=> Use methods that return only info in json

README.md, example.py, src/instabot.py
This commit resolve two problems:
1) When trying execute 'def populate_user_blacklist' it cause error if user account was deleted; 
2) When trying execute 'def populate_user_blacklist' it cause exception if user have no media
=> fix populate_user_blacklist, check_exisiting_comment

README.md
I made a new logo
<a href="#InstaBot" title="Instabot.py Logo"><img src="https://s14.postimg.org/l51bobm8h/Instabot.py.png"></a>
Added the install guide to the top (more importent).
=> Update readme. spelling and reorder.

README.md
Adds Windows and Mac/Linux video tutorials detailing installation of the bot and its dependencies.
=> Add video tutorials to readme

src/instabot.py
Instagram release a new site api version with a new json structure. This PR will fix the bot to work with the new structure
=> support new instagram json structure

src/feed_scanner.py, src/follow_protocol.py, src/post_page.py, src/user_feed.py, src/username_checker.py
feed scanner, follow protocol, post_page, user_feed, username_checker
=> mode 1 base tested revision

src/userinfo.py
Instagram api endpoint changed for user_info (add 'graphql' key)
=> Update user data

src/userinfo.py
Fixes Exception has occurred: AttributeError'NoneType' object has no attribute 'group'
=> Update json_info in userinfo.py

src/instabot.py
Refactored some parts of login function, Handled wrong Username/Pw, Challenge required, Error from Instagram, Other status codes and successful login!
Still has the Challenge problem, Sometimes it works, Sometimes it doesn't
=> Refactored the Login function

src/instabot.py
"spam True" means you have been blocked from liking
=> Clarify reason for 400 response

instabot_py/instabot.py
The problem was in case when end time is less than start time.
For example, I want to run bot from 22:00 to 8:00. It sounds convenient, but logic of mainloop of bot doesn't allow me to do this. The problem was in condition of mainloop.
I implemented function to compute distance between time. The idea is that if end time is less than start time than it means that end time is located on next day. Also I changed condition of mainloop to use that distance and work correctly for all cases.
I have tested my distance function and condition to be sure that everything will be working correctly:
`DNS` is distance between start time and "now"
`DNE` is distance between end time and "now"
For this test start time is `22:00` and end time is `15:00`.
Results:
```
time 0:10
DNS: 1310
DNE: 890
START …
```
=> Fixed problem with sleeping bot. Resolved #2006

instabot_py/instabot.py
Added a feature that prints the instagram media url while trying to comment.
=> Print instagram media url while commenting

sample.instabot.config.yml
=> improved template

instabot_py/instabot.py, instabot_py/persistence/sql.py
If user still follows us or in unfollow whitelist, we need to skip him or her and postpone his or her next checking to follow_time, i.e. set last_follow time as current one.
=> Not unfollow users who follow

instabot_py/instabot.py
Account verification before following action never returned True. This PR fixes this.
=> Fix verify_account for follow action

instabot_py/instabot.py
=> Fix for Proxy Issue
